# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 11:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('title', models.CharField(max_length=50)),
                ('page_count', models.PositiveIntegerField()),
                ('author', models.CharField(max_length=50)),
                ('ISBN_number', models.CharField(max_length=13, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[0-9]{13}$', 'Must be 13 digits with no hyphens')])),
                ('publish_date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libapp.Book')),
            ],
        ),
    ]
