# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import libapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=libapp.models.image_upload_to)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libapp.Book')),
            ],
        ),
        migrations.RenameModel(
            old_name='Genre',
            new_name='BookGenre',
        ),
    ]
